### ISSUE TITLE
a ')' is forgotten in one certain line.

### ISSUE THREAD

**Issue by oneTaken** [Spandan-Madan/A-Collection-of-important-tasks-in-pytorch#1]
in Section4, there is a line:
`self.vismodel = nn.Sequential(*list(model.children())`
It's obviously there is a ')' forgotten in the end of the line.

By the way, can you just rerun the notebook to make the order number is sorted?
Just make more readable.

**Comment by Spandan-Madan** [comment]
Can you make the changes and put in a pull request?

Thanks!

**Comment by Spandan-Madan** [comment]
Merged pull request, closing issue!
